//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Windows.Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Windows.Controls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The modification made to the collection lead to an invalid Selection state. Please check the SelectionMode to allow zero or multiple items..
        /// </summary>
        internal static string Accordion_InvalidManipulationOfSelectionCollections {
            get {
                return ResourceManager.GetString("Accordion_InvalidManipulationOfSelectionCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Should not signal a finish when item is not expected to perform an action..
        /// </summary>
        internal static string Accordion_OnActionFinish_InvalidFinish {
            get {
                return ResourceManager.GetString("Accordion_OnActionFinish_InvalidFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid ExpandDirection value &apos;{0}&apos;..
        /// </summary>
        internal static string Accordion_OnExpandDirectionPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Accordion_OnExpandDirectionPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot set read-only property SelectedIndices..
        /// </summary>
        internal static string Accordion_OnSelectedIndicesChanged_InvalidWrite {
            get {
                return ResourceManager.GetString("Accordion_OnSelectedIndicesChanged_InvalidWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot set read-only property SelectedItems..
        /// </summary>
        internal static string Accordion_OnSelectedItemsChanged_InvalidWrite {
            get {
                return ResourceManager.GetString("Accordion_OnSelectedItemsChanged_InvalidWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid SelectionMode value &apos;{0}&apos;..
        /// </summary>
        internal static string Accordion_OnSelectionModePropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Accordion_OnSelectionModePropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid SelectionSequence value &apos;{0}&apos;..
        /// </summary>
        internal static string Accordion_OnSelectionSequencepropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Accordion_OnSelectionSequencepropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unsupported collection action &apos;{0}&apos;..
        /// </summary>
        internal static string Accordion_UnsupportedCollectionAction {
            get {
                return ResourceManager.GetString("Accordion_UnsupportedCollectionAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ContentTargetSize is a read-only value and is set through Accordion..
        /// </summary>
        internal static string AccordionItem_InvalidWriteToContentTargetSize {
            get {
                return ResourceManager.GetString("AccordionItem_InvalidWriteToContentTargetSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ExpandDirection is a read-only value and is set through Accordion..
        /// </summary>
        internal static string AccordionItem_InvalidWriteToExpandDirection {
            get {
                return ResourceManager.GetString("AccordionItem_InvalidWriteToExpandDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot modify the IsSelected property while item is locked..
        /// </summary>
        internal static string AccordionItem_OnIsSelectedPropertyChanged_InvalidChange {
            get {
                return ResourceManager.GetString("AccordionItem_OnIsSelectedPropertyChanged_InvalidChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid Action &apos;{0}&apos;..
        /// </summary>
        internal static string AccordionItem_StartAction_InvalidAction {
            get {
                return ResourceManager.GetString("AccordionItem_StartAction_InvalidAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot start an action when there is no action scheduled..
        /// </summary>
        internal static string AccordionItem_StartAction_InvalidCall {
            get {
                return ResourceManager.GetString("AccordionItem_StartAction_InvalidCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot perform operation..
        /// </summary>
        internal static string Automation_OperationCannotBePerformed {
            get {
                return ResourceManager.GetString("Automation_OperationCannotBePerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid ExpandDirection value &apos;{0}&apos;..
        /// </summary>
        internal static string Expander_OnExpandDirectionPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Expander_OnExpandDirectionPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Transition &apos;{0}&apos; was not defined..
        /// </summary>
        internal static string TransitioningContentControl_TransitionNotFound {
            get {
                return ResourceManager.GetString("TransitioningContentControl_TransitionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IsTransitioning property is read-only..
        /// </summary>
        internal static string TransitiotioningContentControl_IsTransitioningReadOnly {
            get {
                return ResourceManager.GetString("TransitiotioningContentControl_IsTransitioningReadOnly", resourceCulture);
            }
        }
    }
}
