//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Windows.Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Windows.Controls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid FilterMode enumeration value. The value must be one of the defined AutoCompleteFilterMode values to be accepted..
        /// </summary>
        internal static string AutoComplete_OnFilterModePropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("AutoComplete_OnFilterModePropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid maximum drop down height value &apos;{0}&apos;. The value must be greater than or equal to zero..
        /// </summary>
        internal static string AutoComplete_OnMaxDropDownHeightPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("AutoComplete_OnMaxDropDownHeightPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid MinimumPopulateDelay value &apos;{0}&apos;. The value must be greater than or equal to zero..
        /// </summary>
        internal static string AutoComplete_OnMinimumPopulateDelayPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("AutoComplete_OnMinimumPopulateDelayPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot set read-only property SearchText..
        /// </summary>
        internal static string AutoComplete_OnSearchTextPropertyChanged_InvalidWrite {
            get {
                return ResourceManager.GetString("AutoComplete_OnSearchTextPropertyChanged_InvalidWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot perform operation..
        /// </summary>
        internal static string Automation_OperationCannotBePerformed {
            get {
                return ResourceManager.GetString("Automation_OperationCannotBePerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid index value &apos;{0}&apos;.
        /// </summary>
        internal static string DomainUpDown_CurrentIndex_InvalidValue {
            get {
                return ResourceManager.GetString("DomainUpDown_CurrentIndex_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid InvalidInputAction value &apos;{0}&apos;.
        /// </summary>
        internal static string DomainUpDown_InvalidInputAction_InvalidValue {
            get {
                return ResourceManager.GetString("DomainUpDown_InvalidInputAction_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid ExpandDirection value &apos;{0}&apos;..
        /// </summary>
        internal static string Expander_OnExpandDirectionPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Expander_OnExpandDirectionPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid attempt to change read-only property &quot;{0}.&quot;.
        /// </summary>
        internal static string InvalidAttemptToChangeReadOnlyProperty {
            get {
                return ResourceManager.GetString("InvalidAttemptToChangeReadOnlyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot set read-only property TimeItemsSelection..
        /// </summary>
        internal static string ListTimePickerPopup_TimeItemsSelection_ReadOnly {
            get {
                return ResourceManager.GetString("ListTimePickerPopup_TimeItemsSelection_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid double value &apos;{0}&apos;: valid value is of double type and within decimal range..
        /// </summary>
        internal static string NumericUpDown_EnsureValidDoubleValue_InvalidDoubleValue {
            get {
                return ResourceManager.GetString("NumericUpDown_EnsureValidDoubleValue_InvalidDoubleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid Increment value &apos;{0}&apos;: valid value is of double type, within decimal range, and positive.
        /// </summary>
        internal static string NumericUpDown_EnsureValidIncrementValue_InvalidValue {
            get {
                return ResourceManager.GetString("NumericUpDown_EnsureValidIncrementValue_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid DecimalPlaces value &apos;{0}&apos;: valid value is of int type and within 0 and 15 inclusive..
        /// </summary>
        internal static string NumericUpDown_OnDecimalPlacesPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("NumericUpDown_OnDecimalPlacesPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The collection is currently ReadOnly and should not be modified..
        /// </summary>
        internal static string ObservableObjectCollection_ReadOnly {
            get {
                return ResourceManager.GetString("ObservableObjectCollection_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid maximum drop down height value &apos;{0}&apos;. The value must be greater than or equal to zero..
        /// </summary>
        internal static string Picker_OnMaxDropDownHeightPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Picker_OnMaxDropDownHeightPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid PopupButtonMode value &apos;{0}&apos;..
        /// </summary>
        internal static string Picker_PopupButtonModeNotValid {
            get {
                return ResourceManager.GetString("Picker_PopupButtonModeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value must be larger than or equal to 0..
        /// </summary>
        internal static string Rating_SetItemCount_ItemCountMustBeLargerThanOrEqualToZero {
            get {
                return ResourceManager.GetString("Rating_SetItemCount_ItemCountMustBeLargerThanOrEqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rating.
        /// </summary>
        internal static string RatingAutomationPeer_GetLocalizedControlTypeCore {
            get {
                return ResourceManager.GetString("RatingAutomationPeer_GetLocalizedControlTypeCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value must be null or a number between 0 and 1..
        /// </summary>
        internal static string RatingAutomationPeer_SetValue {
            get {
                return ResourceManager.GetString("RatingAutomationPeer_SetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Star.
        /// </summary>
        internal static string RatingItemAutomationPeer_GetLocalizedControlTypeCore {
            get {
                return ResourceManager.GetString("RatingItemAutomationPeer_GetLocalizedControlTypeCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The RoutedPropertyChangingEvent cannot be canceled..
        /// </summary>
        internal static string RoutedPropertyChangingEventArgs_CancelSet_InvalidOperation {
            get {
                return ResourceManager.GetString("RoutedPropertyChangingEventArgs_CancelSet_InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Spin action is not valid at this moment..
        /// </summary>
        internal static string Spinner_SpinNotValid {
            get {
                return ResourceManager.GetString("Spinner_SpinNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid PopupMinutesInterval &apos;{0}&apos;. The interval can be set to 0 (no interval) to and including 59..
        /// </summary>
        internal static string TimeInput_PopupMinutesInterval_InvalidValue {
            get {
                return ResourceManager.GetString("TimeInput_PopupMinutesInterval_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid PopupSecondsInterval &apos;{0}&apos;.The interval can be set to 0 (no interval) to and including 59..
        /// </summary>
        internal static string TimeInput_PopupSecondsInterval_InvalidValue {
            get {
                return ResourceManager.GetString("TimeInput_PopupSecondsInterval_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot set the PopupProperty in a style. Please use PopupTemplate..
        /// </summary>
        internal static string TimePicker_PopupSetInStyle {
            get {
                return ResourceManager.GetString("TimePicker_PopupSetInStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid PopupTimeSelectionMode for this popup, value &apos;{0}&apos;..
        /// </summary>
        internal static string TimePicker_PopupTimeSelectionModeNotValid {
            get {
                return ResourceManager.GetString("TimePicker_PopupTimeSelectionModeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot set read-only property TimeHintContent..
        /// </summary>
        internal static string TimeUpDown_OnTimeHintContentChanged {
            get {
                return ResourceManager.GetString("TimeUpDown_OnTimeHintContentChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &apos;{0}&apos; is unable to convert &apos;{1}&apos; to &apos;{2}&apos;..
        /// </summary>
        internal static string TypeConverters_Convert_CannotConvert {
            get {
                return ResourceManager.GetString("TypeConverters_Convert_CannotConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &apos;{0}&apos; cannot convert from &apos;{1}&apos;..
        /// </summary>
        internal static string TypeConverters_ConvertFrom_CannotConvertFromType {
            get {
                return ResourceManager.GetString("TypeConverters_ConvertFrom_CannotConvertFromType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot parse text &apos;{0}&apos;.
        /// </summary>
        internal static string UpDown_ParseException {
            get {
                return ResourceManager.GetString("UpDown_ParseException", resourceCulture);
            }
        }
    }
}
